### ISSUE TITLE
Update Changelog format 

### ISSUE THREAD

**Issue by isuftin** [USGS-CIDA/MLR-Notification-Service-Docker#3]
I would siggest updating the Changelog to reflect the format prescribed here: https://keepachangelog.com/en/0.3.0/

**Comment by kmschoep-usgs** [comment]
Other than changing the one label to "Changed" from "Updated", what else needs to change?  We haven't released a version of this yet.

**Comment by isuftin** [comment]
Duh. Never mind. It is already in that format. My bad. I saw a fragment of the log via a PR and thought that was the whole log! 

I'll see myself out
